# Generated by Django 4.2.6 on 2025-06-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_title', models.CharField(blank=True, max_length=200, null=True)),
                ('job_post_url', models.URLField(blank=True, max_length=500, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number1', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_number2', models.CharField(blank=True, max_length=15, null=True)),
                ('person_linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('person_location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
