# Generated by Django 4.2.6 on 2025-06-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posts',
            name='platform_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
